version: '3'
services:

  db_ecommece:
    image: mysql:latest
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: romulo
      MYSQL_PASSWORD: romulo
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
volumes:
  mysql-volume: